# Generated by Django 6.0.5 on 2026-05-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeker',
            name='is_creat',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
