# Generated by Django 6.0.5 on 2026-05-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_seeker_is_creat'),
    ]

    operations = [
        migrations.AddField(
            model_name='emploeer',
            name='is_creat',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
