# Generated by Django 6.0.5 on 2026-05-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_age_alter_user_img_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, default='def.jpg', null=True, upload_to='users/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('seeker', 'Seeker'), ('employer', 'Employer')], max_length=25, null=True),
        ),
    ]
