# Generated by Django 6.0.5 on 2026-05-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_create_at_alter_user_img_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, default='users/def.jpg', null=True, upload_to='users/'),
        ),
    ]
